### ISSUE TITLE
phplint return failures in vendor folder even when this folder excluded

### ISSUE THREAD

**Issue by DarkDrim** [overtrue/phplint#115]
phplint return failures in vendor folder but this folder should be excluded:
I'm using github workflows:
```
- uses: overtrue/phplint@7.4
        with:
          path: ./src
          options: --exclude=vendor
```

I'm receiving now:
FAILURES!
Files: 7843, Failures: 8

There was 8 errors:
1. /github/workspace/src/vendor/yiisoft/yii2/base/Object.php:28
2. /github/workspace/src/vendor/symfony/console/Attribute/AsCommand.php:21
3. etc
all errors from vendor folder
