### ISSUE TITLE
after update: sh: syntax error: unexpected "then"

### ISSUE THREAD

**Issue by drexlma** [overtrue/phplint#174]
i use gitlab. it works many days, but now:
```


test:lint:
  stage: test
  image: overtrue/phplint
  allow_failure: true
  before_script:
  - php -v
  script:
    - composer require overtrue/phplint
    - echo "Syntax checking PHP files"
    - vendor/bin/phplint ./
```

Debug: 
```
Using docker image sha256:1712ab9737368cb7d72eb97192ab7f1aa4a811ebeaddf7765ed4b77034120b05 for overtrue/phplint with digest overtrue/phplint@sha256:173f5155210f68db476378701e96485193cd728a9465dd44a14a307740fff6cb ...
+ '[' '!' -z  ]
+ sh -c '/root/.composer/vendor/bin/phplint sh -c if [ -x /usr/local/bin/bash ]; then
	exec /usr/local/bin/bash 
elif [ -x /usr/bin/bash ]; then
	exec /usr/bin/bash 
elif [ -x /bin/bash ]; then
	exec /bin/bash 
elif [ -x /usr/local/bin/sh ]; then
	exec /usr/local/bin/sh 
elif [ -x /usr/bin/sh ]; then
	exec /usr/bin/sh 
elif [ -x /bin/sh ]; then
	exec /bin/sh 
elif [ -x /busybox/sh ]; then
	exec /busybox/sh 
else
	echo shell not found
	exit 1
fi
'
sh: syntax error: unexpected "then"
```
